# Generated by Django 2.2.24 on 2021-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210712_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='card',
            name='finalization_at',
            field=models.DateTimeField(null=True),
        ),
    ]
